version: "3.7"
services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  server:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: dev-server
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATABASE=test
      - FLASK_DEBUG=1
      - FLASK_APP=./app.py
      # - FLASK_SECRET_KEY=XYZ
      - FLASK_SERVER_NAME=localhost:5000
      # - GOOGLE_CLIENT_ID=ABC
      # - GOOGLE_CLIENT_SECRET=XYZ
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - REDIS_HOST=redis:6379
    ports:
      - "5000:5000" # flask
      - "5678:5678" # debugpy
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
  worker:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: dev-worker
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATABASE=test
      - FLASK_DEBUG=1
      - FLASK_APP=./app.py
      # - FLASK_SECRET_KEY=XYZ
      - FLASK_SERVER_NAME=localhost:5000
      # - GOOGLE_CLIENT_ID=ABC
      # - GOOGLE_CLIENT_SECRET=XYZ
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - REDIS_HOST=redis:6379
    ports:
      - "5679:5678" # debugpy
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
