version: '3.7'
services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
  python:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATABASE=test
      - ACCESS_TOKEN=$ACCESS_TOKEN
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
    # command: [ "python", "-m", "google_photos_deduper" ]
