version: "3.7"
services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - image-volume:/mnt/images
    ports:
      - 80:80
    depends_on:
      - server
      - client
  server:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: dev-server
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATABASE=dev
      - FLASK_DEBUG=1
      - FLASK_APP=./app.py
      # - FLASK_SECRET_KEY=XYZ
      - FLASK_SERVER_NAME=localhost
      - CLIENT_HOST=http://localhost
      # - GOOGLE_CLIENT_ID=ABC
      # - GOOGLE_CLIENT_SECRET=XYZ
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - REDIS_HOST=redis:6379
      - IMAGE_STORE_PATH=/mnt/images/
      - PUBLIC_IMAGE_FOLDER=http://localhost/images/
    ports:
      - "5000:5000" # flask
      - "5678:5678" # debugpy
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
      - image-volume:/mnt/images
  worker:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: dev-worker
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATABASE=dev
      - FLASK_DEBUG=1
      - FLASK_APP=./app.py
      # - FLASK_SECRET_KEY=XYZ
      - FLASK_SERVER_NAME=localhost
      - CLIENT_HOST=http://localhost
      # - GOOGLE_CLIENT_ID=ABC
      # - GOOGLE_CLIENT_SECRET=XYZ
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - REDIS_HOST=redis:6379
      - IMAGE_STORE_PATH=/mnt/images/
      - PUBLIC_IMAGE_FOLDER=http://localhost/images/
    ports:
      - "5679:5678" # debugpy
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
      - image-volume:/mnt/images
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - REACT_APP_SERVER_HOST=http://localhost
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
volumes:
  image-volume:
